# Top of file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: 
        command: |
          python3 -m venv venv
          . venv/bin/active
          pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/active
            python3 messageboard/manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app